quarkus:
  application:
    name: ga-prediction
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://10.1.1.50:5432/warehouse
    reactive:
      url: postgresql://10.1.1.50:5432/warehouse
  http:
    cors: true
  vertx:
    prefer-native-transport: true

mp:
  messaging:
    incoming:
      data-enriched:
        connector: smallrye-kafka
        topic: data.enriched
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      airq-phenotype-created:
        connector: smallrye-kafka
        topic: airq.phenotype.created
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  group:
    id: airq-ga-prediction
  bootstrap:
    servers: 10.1.1.51:9092

"%test":
  pl:
    airq:
      prediction:
        ga:
          domain:
            PredictionClient/mp-rest/url: http://0.0.0.0:${quarkus.http.test-port}
            PredictionClient/mp-rest/scope: javax.enterprise.context.ApplicationScoped
