quarkus:
  application:
    name: ga-prediction
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://10.1.1.50:5432/warehouse
    reactive:
      url: postgresql://10.1.1.50:5432/warehouse
  http:
    cors: true
  vertx:
    prefer-native-transport: true

mp:
  messaging:
    incoming:
      data-enriched:
        connector: smallrye-kafka
        topic: data.enriched
        key:
          deserializer: pl.airq.common.kafka.TSKeyDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      airq-phenotype-created:
        connector: smallrye-kafka
        topic: phenotype.created
        key:
          deserializer: pl.airq.common.kafka.SKeyDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  group:
    id: airq-ga-prediction
  bootstrap:
    servers: 10.1.1.51:9092
